# Generated by Django 3.2.12 on 2022-03-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='professor',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
